language: node_js

node_js:
  - '8'

# Work-around for Chrome.
# See https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-356362524. 
sudo: required

addons:
  # chrome: stable
  # firefox: latest

install:
  - npm install

before_script:
  # - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start &
  # - sleep 3

script:
  - npm run lint
  - npm run test:node
  # - npm run test:browser

after_success:
  - npm run coveralls
